<!DOCTYPE html>
<html>
<head>
    <title>Attendance Report</title>
    <style>
        body { font-family: sans-serif; }
        .header { text-align: center; marginBottom: 20px; }
        .header h1 { margin: 0; color: #4338ca; }
        .header h2 { margin: 5px 0; font-size: 16px; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        table, th, td { border: 1px solid #ddd; }
        th, td { padding: 10px; text-align: left; font-size: 12px; }
        th { background-color: #f3f4f6; }
        .status-present { color: green; font-weight: bold; }
        .status-absent { color: red; font-weight: bold; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Hostel of TPRS</h1>
        <h2>Attendance Report</h2>
        <p>Generated on: {{ now()->format('M d, Y h:i A') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Student Name</th>
                <th>Email</th>
                <th>Room No</th>
                <th>Date</th>
                <th>Time In</th>
                <th>Time Out</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach($attendances as $row)
                <tr>
                    <td>{{ $row->student->name }}</td>
                    <td>{{ $row->student->email }}</td>
                    <td>{{ $row->student->room?->room_number ?? 'Not Assigned' }}</td>
                    <td>{{ \Carbon\Carbon::parse($row->date)->format('M d, Y') }}</td>
                    <td>{{ $row->time_in ? \Carbon\Carbon::parse($row->time_in)->format('h:i A') : '-' }}</td>
                    <td>{{ $row->time_out ? \Carbon\Carbon::parse($row->time_out)->format('h:i A') : '-' }}</td>
                    <td>
                        <span class="status-{{ $row->status }}">
                            {{ ucfirst($row->status) }}
                        </span>
                    </td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Hostel Management System
    </div>
</body>
</html>
